<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="32" started-at="2024-08-16T12:17:35Z" finished-at="2024-08-16T12:17:35Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="32" started-at="2024-08-16T12:17:35Z" finished-at="2024-08-16T12:17:35Z">
      <class name="tesengdemo1.TestNGDemo4">
        <test-method status="FAIL" signature="loginTest()[pri:0, instance:tesengdemo1.TestNGDemo4@73035e27]" name="loginTest" duration-ms="12" started-at="2024-08-16T17:47:35Z" finished-at="2024-08-16T17:47:35Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
	at tesengdemo1.TestNGDemo4.loginTest(TestNGDemo4.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="custumerDetails()[pri:0, instance:tesengdemo1.TestNGDemo4@73035e27]" name="custumerDetails" duration-ms="1" started-at="2024-08-16T17:47:35Z" finished-at="2024-08-16T17:47:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- custumerDetails -->
      </class> <!-- tesengdemo1.TestNGDemo4 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
